config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

   resources :lists do
    resources :bookmarks, only: [ :new, :create ]
   end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie_id, uniqueness: { scope: :list_id, message: "is already in the list" }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  validates :title, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end
  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @bookmark
    @bookmark.save

    redirect_to list_path(@list)
  end

  private
  def set_list
    @list = List.find(params[:list_id])
  end
  def bookmark_params
    params.require(:bookmark).permit(:comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end
  def show
    @list = List.find(params[:id])
  end
  def new
    @list = List.new
  end
  def create
    @list = List.new(list_params) 
    @list.save
    redirect_to list_path(@list)
  end
private
  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>Bookmark</h1>
<p>find me</p>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit "Submit comment", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Watch List" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Lists of movies</h1>
<ul>
  <% @lists.each do |item| %>
    <li><%= link_to item.name, list_path(item) %></li>
  <% end %>
</ul>
 <%= link_to "Add new list!", new_list_path %>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1>list</h1>


<h2><%= @list.name %></h2>
<%= link_to "go back lists " , lists_path%>

app/views/movies/index.html.erb
<h1>Movies</h1>
 <ul>
<% Movies.each do |movie| %>
 </ul>